version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    networks:
      - postgres_nw
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8000:8080'
    depends_on:
      - postgres_db
    networks:
      - postgres_nw

  api:
    restart: always
    build: .
    depends_on:
      - postgres_db
    ports:
      - '5000:5000'
    networks:
      - postgres_nw

networks:
  postgres_nw:

volumes:
  postgres_db:
    driver: local